// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        return web; // ✅ FIX: Linux uses Web Firebase config

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ================= WEB =================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_axFcYmAl0Zd9nDICI3XF32QBPyjk6_c',
    appId: '1:49311526303:web:74c6360c18ec109cd4e1aa',
    messagingSenderId: '49311526303',
    projectId: 'educational-app-8be29',
    authDomain: 'educational-app-8be29.firebaseapp.com',
    storageBucket: 'educational-app-8be29.firebasestorage.app',
    measurementId: 'G-6YQWFBVD87',
  );

  // ================= ANDROID =================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCedHqNv8lI_NDhWZnWJ_PjefNj8RKrA4',
    appId: '1:49311526303:android:a526045c9438de1ed4e1aa',
    messagingSenderId: '49311526303',
    projectId: 'educational-app-8be29',
    storageBucket: 'educational-app-8be29.firebasestorage.app',
  );

  // ================= IOS =================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6QNtEziaSwGylXqMBEMq8-MwKYCny3E',
    appId: '1:49311526303:ios:3fd5292f80573211d4e1aa',
    messagingSenderId: '49311526303',
    projectId: 'educational-app-8be29',
    storageBucket: 'educational-app-8be29.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  // ================= MACOS =================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_6QNtEziaSwGylXqMBEMq8-MwKYCny3E',
    appId: '1:49311526303:ios:3fd5292f80573211d4e1aa',
    messagingSenderId: '49311526303',
    projectId: 'educational-app-8be29',
    storageBucket: 'educational-app-8be29.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  // ================= WINDOWS =================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_axFcYmAl0Zd9nDICI3XF32QBPyjk6_c',
    appId: '1:49311526303:web:9eeaada025fc7c08d4e1aa',
    messagingSenderId: '49311526303',
    projectId: 'educational-app-8be29',
    authDomain: 'educational-app-8be29.firebaseapp.com',
    storageBucket: 'educational-app-8be29.firebasestorage.app',
    measurementId: 'G-E1XNGHLJQJ',
  );
}